= Interpolation, Derivatives and Integrals
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

This section of the math expression user guide covers *interpolation*, *derivatives* and *integrals*.
These three related topics are part of the wider field of numerical analysis.

== Interpolation

Interpolation is used to construct new data points between a set of known control of points.
The ability to predict new data points allows for sampling along the curve defined by the
control points.

The interpolation functions described below return a numeric
array with the predicted values at the control points. Except for the `loess` function,
which is a smoothing interpolator, the interpolation functions return a
numeric array that actually contains the original control points. This is because
interpolation functions predict curves that pass through the control points. At first glance
this seems superflous, but there is more then meets the eye with the interpolation result array.

The interpolation result is also a *function* which can be used to sample values
between the control points. The interpolation result can be passed to other functions
which make use of the sampling capability.

There are different algorithms for interpolation that will result in different predictions
along the curve. The math expressions library currently supports the following
interpolation functions:

* `lerp`: Linear interpolation predicts points that pass through each control point and
  form straight lines between control points.
* `spline`: Spline interpolation predicts points that pass through each control point
and form a smooth curve between control points.
* `akima`: Akima spline interpolation is similar to spline interpolation but is stable to outliers.
* `loess`: Loess interpolation first performs a non-linear local regression to smooth the original
control points. Then a spline is used to interpolate the smoothed control points.

=== Prediction

The `lerp` function performs linear interpolation.
Linear interpolation draws a straight between control points.

[source,text]
----

----

When this expression is sent to the /stream handler it
responds with:

[source,json]
----

----




== Derivatives

The derivative of a function measures the rate of change of the *y* value in respects to the
rate of change of the *x* value.

The `derivative` function returns the derivative value at the control points of an interpolation
function. Different interpolation functions will result in a different derivatives.

A derivative can also be computed for a derivative.

The example below computes a derivative using an `akima` spline interpolation.

[source,text]
----

----

When this expression is sent to the /stream handler it
responds with:

[source,json]
----

----


== Integrals

[source,text]
----

----

When this expression is sent to the /stream handler it
responds with:

[source,json]
----

----

== Bicubic Spline

[source,text]
----

----

When this expression is sent to the /stream handler it
responds with:

[source,json]
----

----

