= Interpolation, Derivatives and Integrals
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

This section of the math expression user guide covers *interpolation*, *derivatives* and *integrals*.
These three related topics are part of the wider field of numerical analysis.

== Interpolation

Interpolation is used to construct new data points between a set of known control of points.
The ability to *predict* new data points allows for *sampling* along the curve defined by the
control points.

The interpolation functions described below all return an *interpolation model*
that can be passed to other functions which make use of the sampling capability.

On its own the interpolation model returns an array containing predictions for each of the
control points. This is useful in the case `loess` interpolation which first smooths the control points
and then interpolates the smoothed points. All other interpolation function simply return the original
control points because interpolation predicts a curve that passes through the original control points.

There are different algorithms for interpolation that will result in different predictions
along the curve. The math expressions library currently supports the following
interpolation functions:

* `lerp`: Linear interpolation predicts points that pass through each control point and
  form straight lines between control points.
* `spline`: Spline interpolation predicts points that pass through each control point
and form a smooth curve between control points.
* `akima`: Akima spline interpolation is similar to spline interpolation but is stable to outliers.
* `loess`: Loess interpolation first performs a non-linear local regression to smooth the original
control points. Then a spline is used to interpolate the smoothed control points.

=== Upsampling

Interpolation can be used to increase the sampling rate along a curve. One example
of this would be to take a time series with samples every minute and create a data set with
samples every second. In order to do this the data points between the minutes must be created.

The `predict` function can be used to predict values anywhere within the bounds of the interpolation
range.  The example below shows a very simple example of upsampling.

In the example linear interpolation is performed on the arrays in variables *x* and *y*. The *x* variable,
which is the x axis, is a sequence from 0 to 20 with a stride of 2. The *y* variable defines the curve
along the x axis.

The `lerp` function performs the interpolation and returns the interpolation model.

The `u` value is an array from 0 to 20 with a stride of 1. This fills in the gaps of the original x axis.
The `predict` function then uses the interpolation function in variable *l* to predict values for
every point in the array assigned to variable *u*.

The variable *p* is the array of predictions, which is the upsampled set of y values.

[source,text]
----
let(x=array(0, 2,  4,  6,  8,   10, 12,  14, 16, 18, 20),
    y=array(5, 10, 60, 190, 100, 130, 100, 20, 30, 10, 5),
    l=lerp(x, y),
    u=array(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20),
    p=predict(l, u))
----

When this expression is sent to the /stream handler it
responds with:

[source,json]
----
{
  "result-set": {
    "docs": [
      {
        "g": [
          5,
          7.5,
          10,
          35,
          60,
          125,
          190,
          145,
          100,
          115,
          130,
          115,
          100,
          60,
          20,
          25,
          30,
          20,
          10,
          7.5,
          5
        ]
      },
      {
        "EOF": true,
        "RESPONSE_TIME": 0
      }
    ]
  }
}
----

=== Smoothing


== Derivatives

The derivative of a function measures the rate of change of the *y* value in respects to the
rate of change of the *x* value.

The `derivative` function returns the derivative value at the control points of an interpolation
function. Different interpolation functions will result in a different derivatives.

A derivative can also be computed for a derivative.

The example below computes a derivative using an `akima` spline interpolation.

[source,text]
----

----

When this expression is sent to the /stream handler it
responds with:

[source,json]
----

----


== Integrals

[source,text]
----

----

When this expression is sent to the /stream handler it
responds with:

[source,json]
----

----

== Bicubic Spline

[source,text]
----

----

When this expression is sent to the /stream handler it
responds with:

[source,json]
----

----

