= Regression and Curve Fitting
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.


This section of the math expressions user guide covers linear and non-linear regression
and curve fitting.

== Linear Regression

=== Simple Linear Regression

The `regress` function is used to build a linear regression model between two numeric arrays.

The example below performs a simple linear regression on a random sample of data.
Each random sample contains two field: response_d and filesize_d. These to
fields are vectorized a stored in variables *b* and *c*.

[source,text]
----
let(a=random(collection2, q="*:*", rows="5000", fl="filesize_d, response_d"),
    b=col(a, filesize_d),
    c=col(a, response_d),
    d=regress(b, c))
----

When this expression is sent to the /stream handler it responds with:

[source,json]
----
{
  "result-set": {
    "docs": [
      {
        "d": {
          "significance": 0,
          "totalSumSquares": 44853.20540050051,
          "R": 0.7991197889322804,
          "RSquared": 0.6385924370631724,
          "meanSquareError": 3.2433548726890447,
          "intercept": -2.3039687269394316,
          "slopeConfidenceInterval": 0.004362798339133255,
          "regressionSumSquares": 28642.917746800664,
          "slope": 0.20913333155786767,
          "interceptStdErr": 0.035400088998122706,
          "N": 5000
        }
      },
      {
        "EOF": true,
        "RESPONSE_TIME": 119
      }
    ]
  }
}
----

==== Prediction

==== Residuals


=== Multivariate Linear Regression

==== Prediction

==== Residuals


== Non-linear Regression and Curve Fitting

== Loess Regression

== Polynomial Curve Fitting



