= Vector Math
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

The math expressions library contains a powerful set of vector math
functions that can be applied in very flexible ways. This section of the guide
describes the different approaches to vector and demonstrate some of
the functions. Other sections of the guide will also cover
vector math as vector math is used in many areas mathematics.

== Arrays

Arrays can be created with `array` function.

For example, the expression below creates a numeric array with
three elements:

[source,text]
----
array(1, 2, 3)
----

When this expression is sent to the /stream handler it responds with
a json array.

[source,json]
----
{
  "result-set": {
    "docs": [
      {
        "return-value": [
          1,
          2,
          3
        ]
      },
      {
        "EOF": true,
        "RESPONSE_TIME": 0
      }
    ]
  }
}
----

== Passing Arrays

Arrays can be passed as a parameter to functions that operate on arrays.

For example, an array can be reversed with the `rev` function:

[source,text]
----
rev(array(1, 2, 3))
----

When this expression is sent to the /stream handler it responds with:

[source,json]
----
{
  "result-set": {
    "docs": [
      {
        "return-value": [
          3,
          2,
          1
        ]
      },
      {
        "EOF": true,
        "RESPONSE_TIME": 0
      }
    ]
  }
}
----

Another example is the `length` function,
which returns the length of an array:

[source,text]
----
length(array(1, 2, 3))
----

When this expression is sent to the /stream handler it responds with:

[source,json]
----
{
  "result-set": {
    "docs": [
      {
        "return-value": 3
      },
      {
        "EOF": true,
        "RESPONSE_TIME": 0
      }
    ]
  }
}
----

== Returning Arrays

Functions can create and return arrays. For example the
`sequence` function generates a sequence of numbers and
returns the sequence as an array. The expression below creates
a sequence of length 3, starting at 0, with a stride of 10.

[source,text]
----
sequence(3, 0, 10)
----

When this expression is sent to the /stream handler it responds with:

[source,json]
----
{
  "result-set": {
    "docs": [
      {
        "return-value": [
          0,
          10,
          20
        ]
      },
      {
        "EOF": true,
        "RESPONSE_TIME": 5
      }
    ]
  }
}
----

== Vector Math

There are a set of functions that perform mathematical
operations on arrays. For example the `scalarMultiply` function
multiplies each element of an array by a scalar value.

The expression below performs the scalar multiplication:

[source,text]
----
scalarMultiply(3, array(1,2,3))
----

When this expression is sent to the /stream handler it responds with:

[source,json]
----
{
  "result-set": {
    "docs": [
      {
        "return-value": [
          3,
          6,
          9
        ]
      },
      {
        "EOF": true,
        "RESPONSE_TIME": 0
      }
    ]
  }
}
----

Arrays can be subtracted with the `ebeSubtract` function which
performs and element-by-element subtract of two arrays.
The expression below performs the element-by-element subtraction.

[source,text]
----
ebeSubtract(array(10, 15, 20), array(1,2,3))
----

When this expression is sent to the /stream handler it responds with:

[source,json]
----
{
  "result-set": {
    "docs": [
      {
        "return-value": [
          9,
          13,
          17
        ]
      },
      {
        "EOF": true,
        "RESPONSE_TIME": 5
      }
    ]
  }
}
----

== Vector Sumarizations

There are also a set of functions that perform
summerizations on arrays. These functions
operate over an array and return a single
summary value.

One example of this is the `mult` function
which multiples all the values of an array.

[source,text]
----
mult(array(2,4,8))
----

When this expression is sent to the /stream handler it responds with:

[source,json]
----
{
  "result-set": {
    "docs": [
      {
        "return-value": 64
      },
      {
        "EOF": true,
        "RESPONSE_TIME": 0
      }
    ]
  }
}
----

Another example of a summary function is
the `l2norm` function which is
commonly used to compute vector magnitude.

The example below performs the l2norm
calculation on an array.

[source,text]
----
l2norm(array(2,4,8))
----

When this expression is sent to the /stream handler it responds with:

[source,json]
----
{
  "result-set": {
    "docs": [
      {
        "return-value": 9.16515138991168
      },
      {
        "EOF": true,
        "RESPONSE_TIME": 0
      }
    ]
  }
}
----

